modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/NerdHubMC/Refined-Machinery/issues"

[[mods]]
    modId="refinedmachinery"
    version="${mod_version}"
    displayName="Refined Machinery"
    displayURL="https://minecraft.curseforge.com/projects/Refined-Machinery"
    authors="abused_master"
    description='''
    A tech mod for mc 1.13.2+
    '''

[[dependencies.refinedmachinery]]
    modId="abusedlib"
    mandatory=true
    versionRange="[1.1.0,)"
    ordering="NONE"
    side="BOTH"